#!/bin/sh
set -e
set -x

DISTRO_RELEASE="el$( lsb_release -sr | awk -F "." '{ print $1 }' )_1"

DEB_RELEASE="$( head debian-common/changelog -n1 | sed 's/.*(\([^)]*\)).*/\1/' )"
RELEASE="$( echo "$DEB_RELEASE" | cut -d '-' -f2 )"
VERSION="$( echo "$DEB_RELEASE" | cut -d '-' -f1 )"

PYTHON_VERSION_MAJOR=$(python3 --version | cut -d ' ' -f2 | cut -d '.' -f1)
PYTHON_VERSION_MINOR=$(python3 --version | cut -d ' ' -f2 | cut -d '.' -f2)

PYTHON_REQUIRES="python${PYTHON_VERSION_MAJOR}${PYTHON_VERSION_MINOR}"
PYTHON_PATH="python${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}"

echo "Setting up for '$DISTRO_RELEASE' Version: '$VERSION' Release: '$RELEASE'"

TOPDIR="$( pwd )/rpmbuild"
SRCDIR="$( pwd )"

mkdir -p "$TOPDIR"
mkdir -p "$TOPDIR/RPMS"
mkdir -p "$TOPDIR/BUILD"
mkdir -p "$TOPDIR/BUILDROOT"

cat > rpmbuild/config.spec <<SPECFILE
%define _topdir $TOPDIR
%define _srcdir $SRCDIR

Name:           respkg
Summary:        RESource PacKaGe
Version:        $VERSION
Release:        $RELEASE.$DISTRO_RELEASE
License:        Apache2
Group:          multiverse/python
Requires:       $PYTHON_REQUIRES, python${PYTHON_VERSION_MAJOR}${PYTHON_VERSION_MINOR}-simplejson
BuildArch:      noarch

%description
respkg - RESource PacKaGe

%install
cd %{_srcdir}
make install DESTDIR=%{buildroot}/

%files
/usr/lib/$PYTHON_PATH/site-packages/*
/usr/bin/*

%changelog

%post

%postun

SPECFILE
